export const INITIALIZE_USERS_REQ = 'INITIALIZE_USERS_REQ';
export const SUCCESS_USERS_REQ = 'SUCCESS_USERS_REQ';
export const COMPLETED_USERS_REQ = 'COMPLETED_USERS_REQ';
export const CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE'
export const CLEAR_SEARCH_VALUE = 'CLEAR_SEARCH_VALUE'
export const FILTER_USERS = 'FILTER_USERS'